export const mockStudents = [
            {
                id: 1,
                name: "Alice Johnson",
                studentId: "ST001",
                riskLevel: "high",
                riskScore: 0.85,
                attendance: 65,
                avgGrade: 2.1,
                lastAssessment: 45,
                course: "Computer Science",
                semester: 3,
                mentorId: "M001",
                mentorName: "Dr. Smith",
                contactInfo: { email: "alice.j@university.edu", phone: "+1234567890" },
                recentActivity: "Missed 3 consecutive classes"
            },
            {
                id: 2,
                name: "Bob Chen",
                studentId: "ST002",
                riskLevel: "medium",
                riskScore: 0.62,
                attendance: 78,
                avgGrade: 2.8,
                lastAssessment: 72,
                course: "Engineering",
                semester: 2,
                mentorId: "M002",
                mentorName: "Prof. Davis",
                contactInfo: { email: "bob.c@university.edu", phone: "+1234567891" },
                recentActivity: "Grade improvement noted"
            },
            {
                id: 3,
                name: "Carol Williams",
                studentId: "ST003",
                riskLevel: "low",
                riskScore: 0.23,
                attendance: 92,
                avgGrade: 3.6,
                lastAssessment: 88,
                course: "Mathematics",
                semester: 4,
                mentorId: "M003",
                mentorName: "Dr. Johnson",
                contactInfo: { email: "carol.w@university.edu", phone: "+1234567892" },
                recentActivity: "Consistent high performance"
            },
            {
                id: 4,
                name: "David Rodriguez",
                studentId: "ST004",
                riskLevel: "high",
                riskScore: 0.78,
                attendance: 58,
                avgGrade: 1.9,
                lastAssessment: 52,
                course: "Business Administration",
                semester: 1,
                mentorId: "M001",
                mentorName: "Dr. Smith",
                contactInfo: { email: "david.r@university.edu", phone: "+1234567893" },
                recentActivity: "Failed two recent exams"
            },
            {
                id: 5,
                name: "Emma Thompson",
                studentId: "ST005",
                riskLevel: "low",
                riskScore: 0.31,
                attendance: 89,
                avgGrade: 3.4,
                lastAssessment: 82,
                course: "Biology",
                semester: 3,
                mentorId: "M004",
                mentorName: "Prof. Anderson",
                contactInfo: { email: "emma.t@university.edu", phone: "+1234567894" },
                recentActivity: "Active in study groups"
            },
            {
                id: 6,
                name: "Frank Miller",
                studentId: "ST006",
                riskLevel: "medium",
                riskScore: 0.58,
                attendance: 72,
                avgGrade: 2.6,
                lastAssessment: 68,
                course: "Chemistry",
                semester: 2,
                mentorId: "M005",
                mentorName: "Dr. Wilson",
                contactInfo: { email: "frank.m@university.edu", phone: "+1234567895" },
                recentActivity: "Struggling with lab work"
            },
            {
                id: 7,
                name: "Grace Lee",
                studentId: "ST007",
                riskLevel: "low",
                riskScore: 0.19,
                attendance: 95,
                avgGrade: 3.8,
                lastAssessment: 94,
                course: "Physics",
                semester: 4,
                mentorId: "M003",
                mentorName: "Dr. Johnson",
                contactInfo: { email: "grace.l@university.edu", phone: "+1234567896" },
                recentActivity: "Top performer in class"
            },
            {
                id: 8,
                name: "Hassan Ali",
                studentId: "ST008",
                riskLevel: "high",
                riskScore: 0.82,
                attendance: 61,
                avgGrade: 2.0,
                lastAssessment: 48,
                course: "Engineering",
                semester: 2,
                mentorId: "M002",
                mentorName: "Prof. Davis",
                contactInfo: { email: "hassan.a@university.edu", phone: "+1234567897" },
                recentActivity: "Multiple assignment delays"
            },
            {
                id: 9,
                name: "Isabella Garcia",
                studentId: "ST009",
                riskLevel: "medium",
                riskScore: 0.45,
                attendance: 83,
                avgGrade: 3.1,
                lastAssessment: 76,
                course: "Literature",
                semester: 3,
                mentorId: "M006",
                mentorName: "Prof. Martinez",
                contactInfo: { email: "isabella.g@university.edu", phone: "+1234567898" },
                recentActivity: "Improved essay writing"
            },
            {
                id: 10,
                name: "Jack O'Connor",
                studentId: "ST010",
                riskLevel: "medium",
                riskScore: 0.52,
                attendance: 76,
                avgGrade: 2.7,
                lastAssessment: 71,
                course: "History",
                semester: 1,
                mentorId: "M007",
                mentorName: "Dr. Thompson",
                contactInfo: { email: "jack.o@university.edu", phone: "+1234567899" },
                recentActivity: "Needs better time management"
            },
            {
                id: 11,
                name: "Kanya Patel",
                studentId: "ST011",
                riskLevel: "low",
                riskScore: 0.26,
                attendance: 91,
                avgGrade: 3.5,
                lastAssessment: 87,
                course: "Computer Science",
                semester: 4,
                mentorId: "M001",
                mentorName: "Dr. Smith",
                contactInfo: { email: "kanya.p@university.edu", phone: "+1234567800" },
                recentActivity: "Excellent coding projects"
            },
            {
                id: 12,
                name: "Liam Brown",
                studentId: "ST012",
                riskLevel: "high",
                riskScore: 0.73,
                attendance: 64,
                avgGrade: 2.2,
                lastAssessment: 56,
                course: "Psychology",
                semester: 2,
                mentorId: "M008",
                mentorName: "Dr. Clark",
                contactInfo: { email: "liam.b@university.edu", phone: "+1234567801" },
                recentActivity: "Attendance issues affecting grades"
            },
            {
                id: 13,
                name: "Maya Singh",
                studentId: "ST013",
                riskLevel: "low",
                riskScore: 0.22,
                attendance: 94,
                avgGrade: 3.7,
                lastAssessment: 91,
                course: "Mathematics",
                semester: 3,
                mentorId: "M003",
                mentorName: "Dr. Johnson",
                contactInfo: { email: "maya.s@university.edu", phone: "+1234567802" },
                recentActivity: "Tutoring other students"
            },
            {
                id: 14,
                name: "Noah Kim",
                studentId: "ST014",
                riskLevel: "medium",
                riskScore: 0.48,
                attendance: 81,
                avgGrade: 2.9,
                lastAssessment: 74,
                course: "Art & Design",
                semester: 1,
                mentorId: "M009",
                mentorName: "Prof. Roberts",
                contactInfo: { email: "noah.k@university.edu", phone: "+1234567803" },
                recentActivity: "Creative but inconsistent"
            },
            {
                id: 15,
                name: "Olivia White",
                studentId: "ST015",
                riskLevel: "medium",
                riskScore: 0.55,
                attendance: 74,
                avgGrade: 2.5,
                lastAssessment: 69,
                course: "Sociology",
                semester: 2,
                mentorId: "M010",
                mentorName: "Dr. Lewis",
                contactInfo: { email: "olivia.w@university.edu", phone: "+1234567804" },
                recentActivity: "Participation declined recently"
            },
            {
                id: 16,
                name: "Peter Zhang",
                studentId: "ST016",
                riskLevel: "low",
                riskScore: 0.18,
                attendance: 96,
                avgGrade: 3.9,
                lastAssessment: 96,
                course: "Engineering",
                semester: 4,
                mentorId: "M002",
                mentorName: "Prof. Davis",
                contactInfo: { email: "peter.z@university.edu", phone: "+1234567805" },
                recentActivity: "Outstanding research project"
            },
            {
                id: 17,
                name: "Quinn Taylor",
                studentId: "ST017",
                riskLevel: "high",
                riskScore: 0.79,
                attendance: 59,
                avgGrade: 1.8,
                lastAssessment: 44,
                course: "Economics",
                semester: 1,
                mentorId: "M011",
                mentorName: "Prof. Green",
                contactInfo: { email: "quinn.t@university.edu", phone: "+1234567806" },
                recentActivity: "Struggling with course concepts"
            },
            {
                id: 18,
                name: "Rachel Adams",
                studentId: "ST018",
                riskLevel: "medium",
                riskScore: 0.41,
                attendance: 85,
                avgGrade: 3.2,
                lastAssessment: 79,
                course: "Biology",
                semester: 3,
                mentorId: "M004",
                mentorName: "Prof. Anderson",
                contactInfo: { email: "rachel.a@university.edu", phone: "+1234567807" },
                recentActivity: "Strong lab performance"
            },
            {
                id: 19,
                name: "Samuel Johnson",
                studentId: "ST019",
                riskLevel: "low",
                riskScore: 0.29,
                attendance: 88,
                avgGrade: 3.3,
                lastAssessment: 84,
                course: "Philosophy",
                semester: 2,
                mentorId: "M012",
                mentorName: "Dr. Harris",
                contactInfo: { email: "samuel.j@university.edu", phone: "+1234567808" },
                recentActivity: "Thoughtful class discussions"
            },
            {
                id: 20,
                name: "Tara Wilson",
                studentId: "ST020",
                riskLevel: "medium",
                riskScore: 0.61,
                attendance: 69,
                avgGrade: 2.4,
                lastAssessment: 65,
                course: "Music",
                semester: 1,
                mentorId: "M013",
                mentorName: "Prof. Cooper",
                contactInfo: { email: "tara.w@university.edu", phone: "+1234567809" },
                recentActivity: "Talented but unfocused"
            }
        ];

export const mockNotifications = [
            {
                id: 1,
                type: "urgent",
                message: "Alice Johnson has been absent for 3 consecutive days",
                timestamp: "2024-09-17 09:30",
                studentId: 1
            },
            {
                id: 2,
                type: "warning",
                message: "Bob Chen's assessment score dropped by 15%",
                timestamp: "2024-09-17 14:22",
                studentId: 2
            },
            {
                id: 3,
                type: "info",
                message: "Monthly risk assessment completed for all students",
                timestamp: "2024-09-17 16:45",
                studentId: null
            }
        ];